export const ADMIN_NAV = [
  { to: '/admin', label: 'Dashboard', icon: 'fa-chart-line' },
  { to: '/admin/locations', label: 'States & Cities', icon: 'fa-map-location-dot' },
  { to: '/admin/users', label: 'Users', icon: 'fa-users' },
  { to: '/admin/clinics', label: 'Clinics', icon: 'fa-hospital' },
  { to: '/admin/conditions', label: 'Conditions', icon: 'fa-notes-medical' },
  { to: '/admin/treatments', label: 'Treatments', icon: 'fa-hand-holding-medical' },
  { to: '/admin/treatment-packages', label: 'Platform packages', icon: 'fa-box-open' },
  { to: '/admin/doctor-packages', label: 'Doctor packages', icon: 'fa-boxes-stacked' },
  { to: '/admin/exercises', label: 'Exercises', icon: 'fa-dumbbell' },
  { to: '/admin/physiofeed', label: 'PhysioFeed', icon: 'fa-rss' },
  { to: '/admin/about', label: 'About Us', icon: 'fa-building' },
  { to: '/admin/badges', label: 'Badges', icon: 'fa-award' },
  { to: '/admin/coupons', label: 'Coupons', icon: 'fa-tag' },
  { to: '/admin/reviews', label: 'Reviews', icon: 'fa-star' },
  { to: '/admin/analytics', label: 'Analytics', icon: 'fa-chart-pie' },
  { to: '/admin/pain-selection', label: 'Pain map', icon: 'fa-bullseye' },
  { to: '/admin/appointments', label: 'Appointments', icon: 'fa-calendar-check' },
  { to: '/admin/appointment-requests', label: 'Doctor changes', icon: 'fa-user-doctor' },
  { to: '/admin/emergency', label: 'Emergency', icon: 'fa-truck-medical' },
  { to: '/admin/booking-settings', label: 'Booking', icon: 'fa-puzzle-piece' },
  { to: '/admin/notifications', label: 'Notifications', icon: 'fa-bell', notifyKey: true },
  { to: '/admin/contact', label: 'Contact & footer', icon: 'fa-envelope' },
  { to: '/admin/home-hero', label: 'Homepage hero', icon: 'fa-house-medical-circle-check' },
  { to: '/admin/home-images', label: 'Homepage images', icon: 'fa-image' },
  { to: '/admin/home-banners', label: 'Homepage banner', icon: 'fa-images' },
  { to: '/admin/invoice-settings', label: 'Invoice', icon: 'fa-file-invoice' },
  { to: '/admin/logs', label: 'Audit Logs', icon: 'fa-clipboard-list' },
  { to: '/admin/profile', label: 'Profile', icon: 'fa-user-gear' },
];
